#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int generator() {
    return (rand() % 900) + 100;  // Generate a random number between 100 and 999
}
void instructions(){
	printf("\n\n============ WELCOME TO THE BULL AND COW GUESSING GAME ============== \n \n");
	printf("Instructions:\n");
	printf("You must guess a \"Three Digit Number\" with unique digits (eg.123,456)\n");
	printf("Clues :\n");
	printf("1.Cow: you have guessed a digit which is the part of the Actual Number (Generated by Computer) but not in the correct position\n");
	printf("\n2.Bull: you have guessed a digit which is the part of the Actual Number and is in the correct position!!\n");
	printf("\n \nExamples:\n");
	printf(" If the computer generated random number is \"678\"\n And You have gussed 690\n Then you will be shown \"1Bull\"-->mean 1digit is in the correct position--in our case \"6\"\n");
	printf("\nAnd if you gussed 961 \n then you will be shown \"1Cow\"-->which mean that one digit is correctly gussed but is not in correct position!\n");
	printf("\nAnd if you gussed 976 then you will be shown \"1Bull,1Cow\"-->which mean one digit is in correct position and the other other digit is gussed correctly but in placed in diffrent position!\n");
	printf("\nAnd finally, if you guess 679, you will see \"2 Bulls\", which means you have guessed two digits correctly, and they are in the correct positions.");
	printf("\n \n\n");
	return;
}
int num_check(int n) {
    int a, b, c;
    do {
        n = generator(); // Function to generate a new random number
        a = n % 10;           
        b = (n / 10) % 10;
        c = (n / 100) % 10;
    } while (a == b || b == c || c == a); 
    return n;
}


int check(int r ,int a){
	int arr1[3];
	int temp = r ;
	for (int i = 0; i < 3; i++)
	{
		arr1[i] = r%10;
		r/=10;
	}
	int arr2[3];
	for (int i = 0; i < 3; i++)
	{
		arr2[i] = a%10;
		a/=10;
	}
	int bull_count=0 , cow_count=0 ;
	for (int i = 0; i < 3; i++)
	{
		for (int j = 0; j < 3; j++)
		{
			if (arr1[i] == arr2[j])
			{
				if (i == j)
				{
					bull_count++;
				}
				else cow_count++;
			}
			
		}
		
	}
	if (bull_count == 0 && cow_count == 0)
	{
		printf("Nothing got mathched, Continue to guess :( ");
	}
	else if (bull_count == 0)
	{
		printf("%d-Cow\n",cow_count);
	}
	else if (cow_count == 0)
	{
		printf("%d-Bull\n",bull_count);
	}
	else{
		printf("%d-Bull , %d-Cow",bull_count,cow_count);
	}
	return 0;
}
int main(){
	int user_input;
	srand(time(0) ^ clock());  
	int rand_num = generator();
	instructions();
	
	printf("ENTER A UNIQUE THREE DIGIT NUMBER(MAKE SURE TO USE UNIQUE DIGITS )\n");
	scanf("%d",&user_input);
	printf("%d\n",rand_num);
	int num_gusess;
	num_check(rand_num);
	do
	{
		check(rand_num,user_input);
		printf("\nNOW ENTER THE NEXT GUESS (-1 to leave) :");
		scanf("%d",&user_input);
		if (user_input == -1)
		{
			break;
		}
		num_gusess++;
	}while(user_input != rand_num);
	if (user_input  == rand_num)
	{
		printf("\nYOU HAVE ENTERD THE PERFECT VALUE IN %d GUESSES\n \n=================   CONGRATULATIONS !!!!  ===============",num_gusess);
		
	}
	
	 return 0 ;
}